
cc_binary(
    name = "cfi",
    srcs = [
        "cfi.cc",
        "register_usage.cc",
        "register_usage.h",
    ],
    deps = [
        "@com_github_gflags_gflags//:gflags",
       	"@dyninst//:dyninst",
        "@glog//:glog",
    ],
)
